export { default as HomePage } from './HomePage';
export { default as AboutPage } from './AboutPage';
export { default as NewsPage } from './NewsPage';
export { default as CareersPage } from './CareersPage';
export { default as ApplyPage } from './ApplyPage';
export { default as InvestorsPage } from './InvestorsPage';
export { default as TechnologyPartnersPage } from './TechnologyPartnersPage';
export { default as LocalPartnersPage } from './LocalPartnersPage';
export { default as PartnershipsPage } from './PartnershipsPage';
export { default as Banks } from './Banks';
export { default as SoftwarePartners } from './SoftwarePartners';
export { default as VisionaryDev } from './VisionaryDev';
export { default as TermsPage } from './TermsPage';
export { default as PrivacyPage } from './PrivacyPage';
export { default as ContactPage } from './ContactPage';
export { default as NotFoundPage } from './NotFoundPage';
export { default as PayInStorePage } from './PayInStorePage';
export { default as PayOnlinePage } from './PayOnlinePage'; 
export { default as BeamForBusiness } from './BeamForBusiness';
export { default as HelpCenter } from './HelpCenter';
export { default as LsInstallationForm } from './LsInstallationForm';
export { default as OsInstallationForm } from './OsInstallationForm';
export {default as InvestorsForm} from './InvestorsForm';
export {default as MobileDeveloper} from './MobileDeveloper';
export {default as JavaScalaDeveloper} from './JavaScalaDeveloper';
export {default as PluginDeveloper} from './PluginDeveloper';
export {default as DiscoverFuture} from './DiscoverFuture';
export {default as GraphicDesigner} from './GraphicDesigner';
export {default as SeoSpecialist} from './SeoSpecialist';
export {default as FullStackWeb3Developer} from './FullStackWeb3Developer';
export {default as Designer} from './Designer';
export {default as SecurityDeveloper} from './SecurityDeveloper';
export {default as SocialMediaSpecialist} from './SocialMediaSpecialist';
export {default as InternationalProjectManager} from './InternationalProjectManager';
export {default as Tester} from './Tester';
export {default as CybersecurityDeveloper} from './CybersecurityDeveloper';
export {default as SalesAgent} from './SalesAgent';
export {default as LpForm} from './LpForm';
export {default as CareerApplicationPage} from './CareerApplicationPage';